// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWB7U6dQQEApekMWaFoQ_dgJWIzXLA-Bo',
    appId: '1:19594974478:web:d82fc1adf0095d3418335f',
    messagingSenderId: '19594974478',
    projectId: 'iubi-a26c0',
    authDomain: 'iubi-a26c0.firebaseapp.com',
    storageBucket: 'iubi-a26c0.firebasestorage.app',
    measurementId: 'G-VJGDWVRK2G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWq7CM8DUH8ZGWHha4gFutwxgaCV8lZK0',
    appId: '1:19594974478:android:aeeb6d9ea9d32a6318335f',
    messagingSenderId: '19594974478',
    projectId: 'iubi-a26c0',
    storageBucket: 'iubi-a26c0.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4o6d5V6cUHBCYxka1g4wKjjj0t25pOxk',
    appId: '1:19594974478:ios:3c370ef9f74703f018335f',
    messagingSenderId: '19594974478',
    projectId: 'iubi-a26c0',
    storageBucket: 'iubi-a26c0.firebasestorage.app',
    androidClientId: '19594974478-h7q84rqsdd36r6guochkbkbfr0kn09lq.apps.googleusercontent.com',
    iosClientId: '19594974478-248ujh2slv4t9bf9gva0t2c1bhm0ee1p.apps.googleusercontent.com',
    iosBundleId: 'com.serviceprovider.iumi',
  );
}
