// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcpCuHKsRjoDkOAfOoT92H5Hrl3HNbtGs',
    appId: '1:344570934631:web:fec9a9525662db01402bc2',
    messagingSenderId: '344570934631',
    projectId: 'serviceprovideriumi',
    authDomain: 'serviceprovideriumi.firebaseapp.com',
    storageBucket: 'serviceprovideriumi.firebasestorage.app',
    measurementId: 'G-DXP80VXNJX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcnSdcDZadf2_Rctszs6AF-MzmmFNAd0Y',
    appId: '1:344570934631:android:a100595b41a1694c402bc2',
    messagingSenderId: '344570934631',
    projectId: 'serviceprovideriumi',
    storageBucket: 'serviceprovideriumi.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyMKaOsSLgOGHFOf4zHa3tFSZwnLprS2I',
    appId: '1:344570934631:ios:20233ecab97f9108402bc2',
    messagingSenderId: '344570934631',
    projectId: 'serviceprovideriumi',
    storageBucket: 'serviceprovideriumi.firebasestorage.app',
    iosBundleId: 'com.example.serviceProviderUmi',
  );
}
