// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWB7U6dQQEApekMWaFoQ_dgJWIzXLA-Bo',
    appId: '1:19594974478:web:d82fc1adf0095d3418335f',
    messagingSenderId: '19594974478',
    projectId: 'iubi-a26c0',
    authDomain: 'iubi-a26c0.firebaseapp.com',
    storageBucket: 'iubi-a26c0.firebasestorage.app',
    measurementId: 'G-VJGDWVRK2G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3zBymrj0SfV1OBcO_ktI4fH487hWeiy0',
    appId: '1:102179953373:android:8cc5c14cacbb3c44211934',
    messagingSenderId: '102179953373',
    projectId: 'service-provider-umi',
    storageBucket: 'service-provider-umi.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMhkfME8ZowWx85LK_7AyW1Gr5X6VglRU',
    appId: '1:102179953373:ios:ef9b76de69a0be84211934',
    messagingSenderId: '102179953373',
    projectId: 'service-provider-umi',
    storageBucket: 'service-provider-umi.firebasestorage.app',
    iosBundleId: 'com.serviceprovider.serviceProviderUmi',
  );
}
