import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

import 'app.dart';
import 'core/config/flavor_config.dart';
// import 'firebase_options.dart'; // Generated by FlutterFire CLI

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // ─── Flavor ─────────────────────────────────────────────
  FlavorConfig.initialize(
    flavor: Flavor.dev,
    baseUrl: 'https://api.dev.yourapp.com/v1',
    socketUrl: 'wss://socket.dev.yourapp.com',
    googleMapsApiKey: 'YOUR_DEV_GOOGLE_MAPS_KEY',
    agoraAppId: 'YOUR_DEV_AGORA_APP_ID',
    stripePublishableKey: 'pk_test_YOUR_STRIPE_KEY',
  );

  // ─── System UI ───────────────────────────────────────────
  await SystemChrome.setPreferredOrientations([
    DeviceOrientation.portraitUp,
    DeviceOrientation.portraitDown,
  ]);

  SystemChrome.setSystemUIOverlayStyle(
    const SystemUiOverlayStyle(
      statusBarColor: Colors.transparent,
      statusBarIconBrightness: Brightness.dark,
      systemNavigationBarColor: Colors.white,
      systemNavigationBarIconBrightness: Brightness.dark,
    ),
  );

  runApp(const ProviderScope(child: App()));
}
